#!/usr/bin/env ruby
# scriptname - HEY DAVE COME DESCRIBE THIS SCRIPT
require "colorize"
require "optimist"
require_relative "dbrady_cli"
String.disable_colorization unless $stdout.tty?

class Application
  include DbradyCli

  def run
    @opts = Optimist.options do
      opt :debug, "Print extra debug info", default: false
      opt :pretend, "Print commands but do not run them", default: false
      opt :quiet, "Run with minimal output", default: false
    end
    end
    puts opts.inspect if opts[:debug]

    # APP CODE GOES HERE
  end

end


if __FILE__ == $0
  Application.new.run
end
