#!/usr/bin/env ruby
# scriptname - new ruby skeleton from refdox. Updated 2023-06-12.
require "colorize"
require "optimist"
String.disable_colorization unless $stdout.tty?

class Application
  attr_reader :opts

  def debug?
    opts[:debug]
  end

  def run
    @opts = Optimist.options do
      opt :debug, "Print extra debug info", default: false
    end

    puts opts.inspect if opts[:debug]
  end

end


if __FILE__ == $0
  Application.new.run
end
