#!/usr/bin/env ruby
# this is currently set as an alias as echo ${COLUMS}x${LINES}
# but this is here to remind me how to do it in ruby ;-)
# ruby -r io/console -e 'y,x = $stdout.winsize; puts "#{x}x#{y}"'
require 'io/console'
y,x = $stdout.winsize
puts "%dx%d" % [x,y]
