#!/bin/bash

# Right now (Ac, circa Spring 2022) we're using Python 3.7 everywhere, so we get
# ordered hashes, but take care not to dip into features from 3.8, 3.9, or 3.10,
# which is currently the latest. 3.7 is in security-fix-only mode and is
# scheduled for End of Life in June 2023.

echo "In Prod: 3.7"
echo "(Note that 3.7 is scheduled for EOL after June 2023.)"
echo "You are currently running:"
echo "python --version"
python --version
