#!/bin/bash
# read-multiple-files-at-once <file1> <file2>

# Cadged from https://stackoverflow.com/questions/42694461/read-from-two-files-line-by-line-and-process-them-simultaneously

while IFS= read -r line1 && IFS= read -r line2 <&3; do
  echo "File 1: $line1"
  echo "File 2: $line2"
done < $1 3< $2
