#!/bin/bash
# sed-print-lines-n-through-m
#
# TIL! I've been doing this with cat -n + grep, or head | tail math. To print lines 100-119:
#
# cat -n file | grep -E '1[01]\d\s'   # with line numbers because cat -n
# head -n 119 file | tail -n 20       # no line numbers
#
# BUT! sed is BUILT to do this out of the box.

echo "Try this:"
echo '  sed -n "2,4p" file1.txt'
echo "See 'man sed' for extended details, but:"
echo "  -n stops sed from printing every line by default"
echo "  [2addr]p tells sed to print the addressed lines"
echo "  2,4 means lines 2-4"
echo "  3 would mean print JUST line 3"

# print lines 2-4 of file1.txt
sed -n "2,4p" file1.txt
